image:
  tag: latest
auth:
  username: coder
  database: coder
shmVolume:
  enabled: true
  sizeLimit: 1Gi
primary:
  resources:
    requests:
      memory: 64Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 200m
  pdb:
    create: false
  networkPolicy:
    enabled: false
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
